### ISSUE TITLE
missing values in SPARQL response

### ISSUE THREAD

**Issue by cmatheus** [marklogic/marklogic-sesame#249] opened 2016-02-26 15:40 UTC
we're having an issue with a SPARQL query response returning invalid JSON.  running the query in qconsole returns the desired result (see below) but when querying it through the ml sesame interface the JSON response returns with some empty values.

in the debugger, when we get to the MarkLogicBackgroundTupleResult we're seeing the following JSON.  Note that the JSON below isn't valid, as the value for the "atTime" has no value.  Note that the query is supposed to be grouping things by "atTime" and counting the number of instances, but all of the "atTime" groups have no value even though the counts have values.

[{
"head": {
"vars": ["atTime", "count"]
},
"results": {
"bindings": [{
"atTime": {
"datatype": "http://www.w3.org/2001/XMLSchema#long",
"type": "literal",
**"value":**
},
"count": {
"datatype": "http://www.w3.org/2001/XMLSchema#unsignedLong",
"type": "literal",
"value": "9"
}
}]
}
},
[{
"head": {
"vars": ["atTime", "count"]
},
"results": {
"bindings": [{
"atTime": {
"datatype": "http://www.w3.org/2001/XMLSchema#long",
"type": "literal",
"value":
},
"count": {
"datatype": "http://www.w3.org/2001/XMLSchema#unsignedLong",
"type": "literal",
"value": "9"
}
}]
}
},
[{
"head": {
"vars": ["atTime", "count"]
},
"results": {
"bindings": [{
"atTime": {
"datatype": "http://www.w3.org/2001/XMLSchema#long",
"type": "literal",
"value":
},
"count": {
"datatype": "http://www.w3.org/2001/XMLSchema#unsignedLong",
"type": "literal",
"value": "9"
}
}]
}
},
[{
"head": {
"vars": ["atTime", "count"]
},
"results": {
"bindings": [{
"atTime": {
"datatype": "http://www.w3.org/2001/XMLSchema#long",
"type": "literal",
"value":
},
"count": {
"datatype": "http://www.w3.org/2001/XMLSchema#unsignedLong",
"type": "literal",
"value": "9"
}
}]
}
}
]]]]

Here's the SPARQL query:

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?atTime (COUNT(?atTime) as ?count)
WHERE {
  VALUES ?subject { <http://localhost:8080/api/doc/1> <inv:http://localhost:8080/api/doc/1> }
  GRAPH ?component {
    ?subject ?predicate ?object .
  }
  GRAPH <urn:provenance> {
    ?component prov:generatedAtTime | prov:invalidatedAtTime ?atTime .
  }
}
GROUP BY ?atTime
ORDER BY DESC (?atTime)
LIMIT 50

And here's a response for that query obtained in qconsole:

[
    {
        "qid": "17812862642620007813",
        "result": [
            {
                "atTime": "\"9223372036854775807\"^^xs:long",
                "count": "\"9\"^^xs:unsignedLong"
            },
            {
                "atTime": "\"1456436222996\"^^xs:long",
                "count": "\"9\"^^xs:unsignedLong"
            }
        ],
        "type": "solution"
    }
]

**Comment by xquery** [comment] 2016-02-26 16:39
Thanks for the bug report.

Would you know if the missing values are null values (or zero) ? Maybe you can provide a sample of a raw triples direct from ML ?

Can you provide version of ML (and java api client), as well as Sesame - that will help me track down where the issue is coming from.

**Comment by xquery** [comment] 2016-02-26 16:44
to be clear - you did include sample from qconsole, can you derive from SPARQL endpoint direct ?

**Comment by cmatheus** [comment] 2016-02-26 19:58
ML version 8.0-4.2
java api client: java-client-api-4.0-SNAPSHOT-sources.jar 
marklogic sesame: marklogic-sesame-1.0.0-SNAPSHOT.jar

the missing values appear to be nulls.
here's an example of hitting the sparql endpoint:

    curl --anyauth -u admin:admin --data-urlencode "query@timemap.sparql" http://localhost:8200/v1/graphs/sparql
    
    {"head":{"vars":["atTime","count"]},"results":{"bindings":[{"atTime":{"datatype":"http://www.w3.org/2001/XMLSchema#long","type":"literal","value":},"count":{"datatype":"http://www.w3.org/2001/XMLSchema#unsignedLong","type":"literal","value":"9"}},{"atTime":{"datatype":"http://www.w3.org/2001/XMLSchema#long","type":"literal","value":"1456493488949"},"count":{"datatype":"http://www.w3.org/2001/XMLSchema#unsignedLong","type":"literal","value":"9"}}]}}

the values are clearly missing here as well.

**Comment by grechaw** [comment] 2016-02-26 21:48
Thanks for the extra info @cmatheus .  This will be a bug either in the REST layer or in serialization.

**Comment by grechaw** [comment] 2016-03-01 18:33
This bug is tracked internally.  We've not been able to diagnose it yet, awaiting sample data for reproduction.

https://bugtrack.marklogic.com/bug/38128

**Comment by xquery** [comment] 2016-03-02 08:41
assigning to @grechaw who will inform when issue in REST layer is sorted (will speak to him today about it)

**Comment by grechaw** [comment] 2016-03-02 17:55
Update is that Fayez checked in a fix to this bug.

**Comment by grechaw** [comment] 2016-03-02 18:00
The symptom by the way is that numbers larger than JavaScript's allowed largest "safe" number are dropped in the results serialization = 9007199254740991 .
So this is something fixed with a server update, no code change needed in sesame or java.
I'll discuss with @kkanthet and @xquery how this bug should be dealt with.

**Comment by grechaw** [comment] 2016-03-15 20:14
Set to test because this is simply waiting on a server release now.

**Comment by grechaw** [comment] 2016-03-29 20:53
With the release of 8.0-5 we can consider this bug fixed.

**Closed** 2016-04-07 06:15 UTC
Labels: Bug, critical, ship
