### ISSUE TITLE
con.clear() deletes everything except the graph document "http://marklogic.com/semantics#default-graph"

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#107] opened 2015-08-13 08:25 UTC
con.clear() deletes everything except the graph document "http://marklogic.com/semantics#default-graph". All triples in the default graph are deleted but the graph document alone remains and is not deleted.  All named graph documents ARE deleted.

**Comment by xquery** [comment] 2015-08-14 16:58
dep on java api client

**Comment by xquery** [comment] 2015-08-14 19:49
after discussion with Charles, we agreed that this is not a bug and marking as enhancement for future discussion

**Closed** 2015-08-14 19:49 UTC
Labels: Bug, minor
